### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 프로젝트 조회
GET http://localhost:8001/api/v1/pjts
Access-Token: Bearer eyJkYXRlIjoxNzI1OTUzNjgxMDMwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsIm1lbWJlcklkIjoidXNlcjAxIiwibWVtYmVyUm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcyNTk1NzI4MX0.u_a2FJ8ypmJ84JvPfu4niumeH0rjxpRCf4ZitpuiIZDB8X29z-B7Xg0EmiwgItu2KfLpAMes9fqTwsTbsA8y6w

### 프로젝트 생성
POST http://localhost:8001/api/v1/pjts
Access-Token: Bearer eyJkYXRlIjoxNzI2MTE4MDMxNTc2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsIm1lbWJlcklkIjoidXNlcjAxIiwibWVtYmVyUm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcyNjEyMTYzMX0.MQmNyEFmmt6FVqWxXBSIBj5rt1csZFwv9-4Go5v8AXwW5BZ6jt8AQpPcMA9-T1cLhKG5HVUoTr33sL2GC4R2hA
Content-Type: application/json

{
  "pjtName": "테스트용 이름3"
}

### 프로젝트 수정
PUT http://localhost:8001/api/v1/pjts/1
Access-Token: Bearer eyJkYXRlIjoxNzI2MDQwODE0MjAyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsIm1lbWJlclJvbGUiOiJST0xFX1VTRVIiLCJtZW1iZXJJZCI6InVzZXIwMSIsImV4cCI6MTcyNjA0NDQxNH0.cqIEj5svRvrG7tNX4q6cgacSU6hyQ2TjE9fMhcM1miQfhqhtUEjBms1hISuVpRUH7HfZwUFQk92iAXJU2vtApQ
Content-Type: application/json

{
  "pjtName": "수정된 이름"
}

### 프로젝트 삭제
DELETE http://localhost:8001/api/v1/pjt/1
Access-Token: Bearer eyJkYXRlIjoxNzI2MDQwODE0MjAyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsIm1lbWJlclJvbGUiOiJST0xFX1VTRVIiLCJtZW1iZXJJZCI6InVzZXIwMSIsImV4cCI6MTcyNjA0NDQxNH0.cqIEj5svRvrG7tNX4q6cgacSU6hyQ2TjE9fMhcM1miQfhqhtUEjBms1hISuVpRUH7HfZwUFQk92iAXJU2vtApQ

### 프로젝트에 속한 패이지 목록조회
GET http://localhost:8001/api/v1/pjts/pages/2
Access-Token: Bearer eyJkYXRlIjoxNzI2MTE4MDMxNTc2LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJzdWIiOiJBY2Nlc3NUb2tlbiIsIm1lbWJlcklkIjoidXNlcjAxIiwibWVtYmVyUm9sZSI6IlJPTEVfVVNFUiIsImV4cCI6MTcyNjEyMTYzMX0.MQmNyEFmmt6FVqWxXBSIBj5rt1csZFwv9-4Go5v8AXwW5BZ6jt8AQpPcMA9-T1cLhKG5HVUoTr33sL2GC4R2hA
